cx-flow:
  enabled-vulnerability-scanners:
    - sca
  branches:
    - develop
    - master
    - security
    - main
sca:
  appUrl: ${ AGENT_INTERNAL_URL }
  apiUrl: ${ AGENT_INTERNAL_URL }
  accessControlUrl: ${ AGENT_INTERNAL_URL }
  tenant: ${ SCA_TENANT }
  username: ${ SCA_USERNAME }
  password: ${ SCA_PASSWORD }

github:
  webhook-token: ${ WEBHOOK_TOKEN }
  token: ${ TOKEN }
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  config-as-code:
  block-merge: true
  detailed: false
  error-merge: true
  cx-summary: false
  flow-summary: true
